### Term Project
### DSC 540
### Abed Tabbalat

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from bs4 import BeautifulSoup
import codecs
import requests
import json

This project is about Covid-19 data, will reformat data into the best shape possible from three sources and combine the necassary variables to give an output to inform viewers on highly important results regarding the pandemic.

In [2]:
# Settings
#Pandas number format settings to be set at 0 decimat places
# Step 5 adjusting pandas settings for formatting figures
pd.options.display.float_format = '{:,.0f}'.format

# Milestone 2

In [3]:
# In this milestone, we will perform data wrangling techniques on the flat file that contains
# data on daily vaccinations by country
# The unique key identifier in all sources will be country
# Step 1 to import the flat file using Pandas
df_flat_raw = pd.read_csv('country_vaccinations.csv')
df_flat_raw.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0,0,NaN,NaN,NaN,0,0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

In [4]:
# Before doing any altering exercise, I will create a new variable name to keep the raw data stored as it is
# Will need to change the column names, in order to do that we need to see what the column names are
# Will use the list() function to call a list of the column names
df_flat = df_flat_raw
list(df_flat.columns)

['country',
 'iso_code',
 'date',
 'total_vaccinations',
 'people_vaccinated',
 'people_fully_vaccinated',
 'daily_vaccinations_raw',
 'daily_vaccinations',
 'total_vaccinations_per_hundred',
 'people_vaccinated_per_hundred',
 'people_fully_vaccinated_per_hundred',
 'daily_vaccinations_per_million',
 'vaccines',
 'source_name',
 'source_website']

In [5]:
# Step 2: Updating column headers using the column attribute:
df_flat.columns = ['Country', 'ISO Code', 'Date','Total Vaccinations', 
                    'People Vaccinated', 'People Fully Vaccinated', 'Daily Vaccinations Raw',
                    'Daily Vaccinations', 'Total Vaccinations/100', 'People Vaccinated/100', 
                    'People Fully Vaccinated/100', 'Daily Vaccinations/Mil', 'Vaccines',
                    'Source Name Vaccinations', 'Source Website Vaccinations']
df_flat.head()

,Country,ISO Code,Date,Total Vaccinations,People Vaccinated,People Fully Vaccinated,Daily Vaccinations Raw,Daily Vaccinations,Total Vaccinations/100,People Vaccinated/100,People Fully Vaccinated/100,Daily Vaccinations/Mil,Vaccines,Source Name Vaccinations,Source Website Vaccinations
0,Afghanistan,AFG,2021-02-22,0,0,NaN,NaN,NaN,0,0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

In [6]:
# Step 3: is to remove columns that wont be needed for the project
# The columns that will remain are shown below
df_flat_1 = df_flat[['Country', 'Total Vaccinations', 'People Vaccinated']]
df_flat_1

           Country  Total Vaccinations  People Vaccinated
0      Afghanistan                   0                  0
1      Afghanistan                 NaN                NaN
2      Afghanistan                 NaN                NaN
3      Afghanistan                 NaN                NaN
4      Afghanistan                 NaN                NaN
...            ...                 ...                ...
71810     Zimbabwe           7,432,819          4,204,134
71811     Zimbabwe           7,438,485          4,206,370
71812     Zimbabwe           7,446,076          4,210,000
71813     Zimbabwe           7,458,519          4,216,112
71814     Zimbabwe           7,472,553          4,223,110

[71815 rows x 3 columns]

In [7]:
# Step 4: will summarize the data to have 1 country as a unique ID by using groupby() function
# Using mean since some countries have missing reported dates of vaccinations
df_flat_1 = df_flat_1.groupby('Country').mean().reset_index()
df_flat_1

               Country  Total Vaccinations  People Vaccinated
0          Afghanistan           1,588,162          1,335,322
1              Albania           1,095,255            727,809
2              Algeria           9,435,633          5,414,206
3              Andorra              44,010             29,327
4               Angola           4,244,810          2,800,567
..                 ...                 ...                ...
218              Wales           3,626,606          1,931,716
219  Wallis and Futuna               8,834              4,836
220              Yemen             318,941            265,881
221             Zambia             638,290            187,488
222           Zimbabwe           3,348,647          1,966,053

[223 rows x 3 columns]

In [8]:
# Step 5 is to check for duplicates
print(f'Any duplicated country: {any(df_flat_1.duplicated())}')
# Result confirms no duplicates

Any duplicated country: False

In [9]:
# Step 6 is to check for NULLS in the dataframe
print(f'Any NULLS in Total Vaccinations: {df_flat_1["Total Vaccinations"].isnull().values.any()}')
print(f'Any NULLS in People Vaccinated: {df_flat_1["People Vaccinated"].isnull().values.any()}')
# Result makes sense because using the groupby() function and applying mean() should eliminate the NULLS

Any NULLS in Total Vaccinations: False
Any NULLS in People Vaccinated: False

In [10]:
# Step 7: Data shape is ready for phase 2.
df_flat_1

               Country  Total Vaccinations  People Vaccinated
0          Afghanistan           1,588,162          1,335,322
1              Albania           1,095,255            727,809
2              Algeria           9,435,633          5,414,206
3              Andorra              44,010             29,327
4               Angola           4,244,810          2,800,567
..                 ...                 ...                ...
218              Wales           3,626,606          1,931,716
219  Wallis and Futuna               8,834              4,836
220              Yemen             318,941            265,881
221             Zambia             638,290            187,488
222           Zimbabwe           3,348,647          1,966,053

[223 rows x 3 columns]

# Milestone 3

In [11]:
# using pandas to read html. had issues with forbidden HTTP and therefore I used the help of a post in
# stackoverflow to import the requests package and place the header to call the HTML site
url = 'https://www.worldometers.info/world-population/population-by-country/'
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

In [12]:
# Used the requests.get function to call the website (similar to APIs) and the table is now readable.
r = requests.get(url, headers=header)
dfs_web = pd.read_html(r.text)

In [13]:
# Checking how many dataframes the website contains. Looking at the web page there is only one table
len(dfs_web)

1

In [14]:
# defining the table to begin data wrangling process.
df_web_raw = dfs_web[0]
df_web_raw

,#,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,1,China,1439323776,0.39 %,5540090,153,9388211,"-348,399",1.7,38,61 %,18.47 %
1,2,India,1380004385,0.99 %,13586631,464,2973190,"-532,687",2.2,28,35 %,17.70 %
2,3,United States,331002651,0.59 %,1937734,36,9147420,"954,806",1.8,38,83 %,4.25 %
3,4,Indonesia,273523615,1.07 %,2898047,151,1811570,"-98,955",2.3,30,56 %,3.51 %
4,5,Pakistan,220892340,2.00 %,4327022,287,770880,"-233,379",3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,233,Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [15]:
# Step 1: Updating column headers using the column attribute:
# Will call a list to see the full column names
df_web = df_web_raw
list(df_web.columns)

['#',
 'Country (or dependency)',
 'Population (2020)',
 'Yearly Change',
 'Net Change',
 'Density (P/Km²)',
 'Land Area (Km²)',
 'Migrants (net)',
 'Fert. Rate',
 'Med. Age',
 'Urban Pop %',
 'World Share']

In [16]:
# Renaming columns for more clarity.
df_web.columns = ['#', 'Country', 'Population', 'Yearly Change', 'Net Change', 'Density', 'Land Area', 
                  'Migrants', 'Fertility Rate', 'Median Age', 'Urban Population Percentage', 'World Share']
df_web

,#,Country,Population,Yearly Change,Net Change,Density,Land Area,Migrants,Fertility Rate,Median Age,Urban Population Percentage,World Share
0,1,China,1439323776,0.39 %,5540090,153,9388211,"-348,399",1.7,38,61 %,18.47 %
1,2,India,1380004385,0.99 %,13586631,464,2973190,"-532,687",2.2,28,35 %,17.70 %
2,3,United States,331002651,0.59 %,1937734,36,9147420,"954,806",1.8,38,83 %,4.25 %
3,4,Indonesia,273523615,1.07 %,2898047,151,1811570,"-98,955",2.3,30,56 %,3.51 %
4,5,Pakistan,220892340,2.00 %,4327022,287,770880,"-233,379",3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,233,Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [17]:
# Step 2 will need from this dataset the Country column and the Population column as the rest of the data
# is irrelevant to this project
df_web_1 = df_web[['Country', 'Population']]
df_web_1

              Country  Population
0               China  1439323776
1               India  1380004385
2       United States   331002651
3           Indonesia   273523615
4            Pakistan   220892340
..                ...         ...
230        Montserrat        4992
231  Falkland Islands        3480
232              Niue        1626
233           Tokelau        1357
234          Holy See         801

[235 rows x 2 columns]

In [18]:
# Step 3 is to make sure there are no NA's or N.A (this was visible in the original dataframe).
# first replacing N.A. (if any) to None to give NaNs that Pandas identify.
df_web_1.replace('N.A.', None)

              Country  Population
0               China  1439323776
1               India  1380004385
2       United States   331002651
3           Indonesia   273523615
4            Pakistan   220892340
..                ...         ...
230        Montserrat        4992
231  Falkland Islands        3480
232              Niue        1626
233           Tokelau        1357
234          Holy See         801

[235 rows x 2 columns]

In [19]:
# Checking for NaNs and Duplicates
print(f'Any duplicated country: {any(df_web_1.duplicated())}')
print(f'Any NULLS in Population: {df_web_1["Population"].isnull().values.any()}')
# Result shows no duplicates nor NaNs

Any duplicated country: False
Any NULLS in Population: False

In [20]:
# Step 4 updating the Population column format
# Population column not being formatted and this is because is set as int and will convert to float
# first step is to use dtypes on the dataframe to determine which columns needs to be changed
df_web_1.dtypes

Country       object
Population     int64
dtype: object

In [21]:
# Will change the Population column type to float by using astype() function
df_web_1 = df_web_1.astype({'Population' : 'float64'})

In [22]:
# Data is in shape and ready for Phase 2
df_web_1

              Country    Population
0               China 1,439,323,776
1               India 1,380,004,385
2       United States   331,002,651
3           Indonesia   273,523,615
4            Pakistan   220,892,340
..                ...           ...
230        Montserrat         4,992
231  Falkland Islands         3,480
232              Niue         1,626
233           Tokelau         1,357
234          Holy See           801

[235 rows x 2 columns]

# Milestone 4

In [48]:
# Calling api url using requests library
api_url = 'https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases2_v1/FeatureServer/2/query?where=1%3D1&outFields=*&returnGeometry=false&outSR=4326&f=json'
response = requests.get(api_url)
response
# 200 means the request is successful

In [49]:
# Extracting data from the request using json()
json = response.json()
json

{'objectIdFieldName': 'OBJECTID',
 'uniqueIdField': {'name': 'OBJECTID', 'isSystemMaintained': True},
 'globalIdFieldName': '',
 'geometryType': 'esriGeometryPoint',
 'spatialReference': {'wkid': 4326, 'latestWkid': 4326},
 'fields': [{'name': 'OBJECTID',
   'type': 'esriFieldTypeOID',
   'alias': 'OBJECTID',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'Country_Region',
   'type': 'esriFieldTypeString',
   'alias': 'Country/Region',
   'sqlType': 'sqlTypeOther',
   'length': 256,
   'domain': None,
   'defaultValue': None},
  {'name': 'Last_Update',
   'type': 'esriFieldTypeDate',
   'alias': 'Last Update',
   'sqlType': 'sqlTypeOther',
   'length': 8,
   'domain': None,
   'defaultValue': None},
  {'name': 'Lat',
   'type': 'esriFieldTypeDouble',
   'alias': 'Latitude',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'Long_',
   'type': 'esriFieldTypeDouble',
   'alias': 'Longitude',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'Confirmed',
   'type': 'esriFieldTypeInteger',
   'alias': 'Confirmed',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'Deaths',
   'type': 'esriFieldTypeInteger',
   'alias': 'Deaths',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'Recovered',
   'type': 'esriFieldTypeInteger',
   'alias': 'Recovered',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'Active',
   'type': 'esriFieldTypeInteger',
   'alias': 'Active',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'Incident_Rate',
   'type': 'esriFieldTypeDouble',
   'alias': 'Incident Rate',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'People_Tested',
   'type': 'esriFieldTypeInteger',
   'alias': 'People Tested',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'People_Hospitalized',
   'type': 'esriFieldTypeInteger',
   'alias': 'People_Hospitalized',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'Mortality_Rate',
   'type': 'esriFieldTypeDouble',
   'alias': 'Mortality_Rate',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'UID',
   'type': 'esriFieldTypeInteger',
   'alias': 'UID',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'ISO3',
   'type': 'esriFieldTypeString',
   'alias': 'ISO3',
   'sqlType': 'sqlTypeOther',
   'length': 3,
   'domain': None,
   'defaultValue': None}],
 'features': [{'attributes': {'OBJECTID': 1,
    'Country_Region': 'Afghanistan',
    'Last_Update': 1644862830000,
    'Lat': 33.93911,
    'Long_': 67.709953,
    'Confirmed': 171246,
    'Deaths': 7501,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 439.90058553998,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 4.38024829777046,
    'UID': 4,
    'ISO3': 'AFG'}},
  {'attributes': {'OBJECTID': 2,
    'Country_Region': 'Albania',
    'Last_Update': 1644862830000,
    'Lat': 41.1533,
    'Long_': 20.1683,
    'Confirmed': 268304,
    'Deaths': 3414,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 9323.2330252276,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.2724372353748,
    'UID': 8,
    'ISO3': 'ALB'}},
  {'attributes': {'OBJECTID': 3,
    'Country_Region': 'Algeria',
    'Last_Update': 1644862830000,
    'Lat': 28.0339,
    'Long_': 1.6596,
    'Confirmed': 261752,
    'Deaths': 6729,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 596.911685772218,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 2.57075399614903,
    'UID': 12,
    'ISO3': 'DZA'}},
  {'attributes': {'OBJECTID': 4,
    'Country_Region': 'Andorra',
    'Last_Update': 1644862830000,
    'Lat': 42.5063,
    'Long_': 1.5218,
    'Confirmed': 37140,
    'Deaths': 148,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 48068.3362453892,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.398492191707054,
    'UID': 20,
    'ISO3': 'AND'}},
  {'attributes': {'OBJECTID': 5,
    'Country_Region': 'Angola',
    'Last_Update': 1644862830000,
    'Lat': -11.2027,
    'Long_': 17.8739,
    'Confirmed': 98514,
    'Deaths': 1898,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 299.741972529403,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.92662971760359,
    'UID': 24,
    'ISO3': 'AGO'}},
  {'attributes': {'OBJECTID': 6,
    'Country_Region': 'Antarctica',
    'Last_Update': 1644862830000,
    'Lat': -71.9499,
    'Long_': 23.347,
    'Confirmed': 11,
    'Deaths': 0,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': None,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0,
    'UID': 10,
    'ISO3': 'ATA'}},
  {'attributes': {'OBJECTID': 7,
    'Country_Region': 'Antigua and Barbuda',
    'Last_Update': 1644862830000,
    'Lat': 17.0608,
    'Long_': -61.7964,
    'Confirmed': 7331,
    'Deaths': 134,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 7486.11224573156,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.82785431728277,
    'UID': 28,
    'ISO3': 'ATG'}},
  {'attributes': {'OBJECTID': 8,
    'Country_Region': 'Argentina',
    'Last_Update': 1644862830000,
    'Lat': -38.4161,
    'Long_': -63.6167,
    'Confirmed': 8734551,
    'Deaths': 124081,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 19326.0334920229,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.42057674172376,
    'UID': 32,
    'ISO3': 'ARG'}},
  {'attributes': {'OBJECTID': 9,
    'Country_Region': 'Armenia',
    'Last_Update': 1644862830000,
    'Lat': 40.0691,
    'Long_': 45.0382,
    'Confirmed': 407074,
    'Deaths': 8186,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 13737.4908630233,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 2.01093658646831,
    'UID': 51,
    'ISO3': 'ARM'}},
  {'attributes': {'OBJECTID': 10,
    'Country_Region': 'Australia',
    'Last_Update': 1644862830000,
    'Lat': -25,
    'Long_': 133,
    'Confirmed': 2921725,
    'Deaths': 4618,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 11475.8814911409,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.158057312033131,
    'UID': 36,
    'ISO3': 'AUS'}},
  {'attributes': {'OBJECTID': 11,
    'Country_Region': 'Austria',
    'Last_Update': 1644862830000,
    'Lat': 47.5162,
    'Long_': 14.5501,
    'Confirmed': 2299229,
    'Deaths': 14392,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 25528.8350506307,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.625948959412046,
    'UID': 40,
    'ISO3': 'AUT'}},
  {'attributes': {'OBJECTID': 12,
    'Country_Region': 'Azerbaijan',
    'Last_Update': 1644862830000,
    'Lat': 40.1431,
    'Long_': 47.5769,
    'Confirmed': 747918,
    'Deaths': 9077,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 7376.51732019617,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.21363571942379,
    'UID': 31,
    'ISO3': 'AZE'}},
  {'attributes': {'OBJECTID': 13,
    'Country_Region': 'Bahamas',
    'Last_Update': 1644862830000,
    'Lat': 25.025885,
    'Long_': -78.035889,
    'Confirmed': 32931,
    'Deaths': 766,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 8374.10489055253,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 2.32607573411072,
    'UID': 44,
    'ISO3': 'BHS'}},
  {'attributes': {'OBJECTID': 14,
    'Country_Region': 'Bahrain',
    'Last_Update': 1644862830000,
    'Lat': 26.0275,
    'Long_': 50.55,
    'Confirmed': 463805,
    'Deaths': 1427,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 27257.2657343192,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.307672405429006,
    'UID': 48,
    'ISO3': 'BHR'}},
  {'attributes': {'OBJECTID': 15,
    'Country_Region': 'Bangladesh',
    'Last_Update': 1644862830000,
    'Lat': 23.685,
    'Long_': 90.3563,
    'Confirmed': 1914356,
    'Deaths': 28838,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 1162.40401483561,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.50640737668438,
    'UID': 50,
    'ISO3': 'BGD'}},
  {'attributes': {'OBJECTID': 16,
    'Country_Region': 'Barbados',
    'Last_Update': 1644862830000,
    'Lat': 13.1939,
    'Long_': -59.5432,
    'Confirmed': 51624,
    'Deaths': 299,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 17964.2343869075,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.579187974585464,
    'UID': 52,
    'ISO3': 'BRB'}},
  {'attributes': {'OBJECTID': 17,
    'Country_Region': 'Belarus',
    'Last_Update': 1644862830000,
    'Lat': 53.7098,
    'Long_': 27.9534,
    'Confirmed': 838571,
    'Deaths': 6265,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 8874.4048381889,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.747104300053305,
    'UID': 112,
    'ISO3': 'BLR'}},
  {'attributes': {'OBJECTID': 18,
    'Country_Region': 'Belgium',
    'Last_Update': 1644862830000,
    'Lat': 50.8333,
    'Long_': 4.469936,
    'Confirmed': 3421081,
    'Deaths': 29624,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 29767.5790969195,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.865925127174715,
    'UID': 56,
    'ISO3': 'BEL'}},
  {'attributes': {'OBJECTID': 19,
    'Country_Region': 'Belize',
    'Last_Update': 1644862830000,
    'Lat': 17.1899,
    'Long_': -88.4976,
    'Confirmed': 55183,
    'Deaths': 631,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 13878.2911365345,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.14346809705888,
    'UID': 84,
    'ISO3': 'BLZ'}},
  {'attributes': {'OBJECTID': 20,
    'Country_Region': 'Benin',
    'Last_Update': 1644862830000,
    'Lat': 9.3077,
    'Long_': 2.3158,
    'Confirmed': 26552,
    'Deaths': 163,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 219.018117166774,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.61388972582103,
    'UID': 204,
    'ISO3': 'BEN'}},
  {'attributes': {'OBJECTID': 21,
    'Country_Region': 'Bhutan',
    'Last_Update': 1644862830000,
    'Lat': 27.5142,
    'Long_': 90.4336,
    'Confirmed': 7666,
    'Deaths': 5,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 993.504507446748,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.0652230628750326,
    'UID': 64,
    'ISO3': 'BTN'}},
  {'attributes': {'OBJECTID': 22,
    'Country_Region': 'Bolivia',
    'Last_Update': 1644862830000,
    'Lat': -16.2902,
    'Long_': -63.5887,
    'Confirmed': 883382,
    'Deaths': 21284,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 7567.71871294075,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 2.40937669094457,
    'UID': 68,
    'ISO3': 'BOL'}},
  {'attributes': {'OBJECTID': 23,
    'Country_Region': 'Bosnia and Herzegovina',
    'Last_Update': 1644862830000,
    'Lat': 43.9159,
    'Long_': 17.6791,
    'Confirmed': 364610,
    'Deaths': 15096,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 11113.3971284574,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 4.14031430843915,
    'UID': 70,
    'ISO3': 'BIH'}},
  {'attributes': {'OBJECTID': 24,
    'Country_Region': 'Botswana',
    'Last_Update': 1644862830000,
    'Lat': -22.3285,
    'Long_': 24.6849,
    'Confirmed': 259655,
    'Deaths': 2597,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 11041.5138468081,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.00017330688799,
    'UID': 72,
    'ISO3': 'BWA'}},
  {'attributes': {'OBJECTID': 25,
    'Country_Region': 'Brazil',
    'Last_Update': 1644862830000,
    'Lat': -14.235,
    'Long_': -51.9253,
    'Confirmed': 27492904,
    'Deaths': 638673,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 12934.2211334432,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 2.32304670325114,
    'UID': 76,
    'ISO3': 'BRA'}},
  {'attributes': {'OBJECTID': 26,
    'Country_Region': 'Brunei',
    'Last_Update': 1644862830000,
    'Lat': 4.5353,
    'Long_': 114.7277,
    'Confirmed': 23992,
    'Deaths': 98,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 5484.09881069664,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.408469489829943,
    'UID': 96,
    'ISO3': 'BRN'}},
  {'attributes': {'OBJECTID': 27,
    'Country_Region': 'Bulgaria',
    'Last_Update': 1644862830000,
    'Lat': 42.7339,
    'Long_': 25.4858,
    'Confirmed': 1036824,
    'Deaths': 34404,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 14921.6695246203,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 3.31821022661512,
    'UID': 100,
    'ISO3': 'BGR'}},
  {'attributes': {'OBJECTID': 28,
    'Country_Region': 'Burkina Faso',
    'Last_Update': 1644862830000,
    'Lat': 12.2383,
    'Long_': -1.5616,
    'Confirmed': 20721,
    'Deaths': 375,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 99.1279932267083,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.8097582163023,
    'UID': 854,
    'ISO3': 'BFA'}},
  {'attributes': {'OBJECTID': 29,
    'Country_Region': 'Burma',
    'Last_Update': 1644862830000,
    'Lat': 21.9162,
    'Long_': 95.956,
    'Confirmed': 548357,
    'Deaths': 19311,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 1007.82774512986,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 3.52161092135233,
    'UID': 104,
    'ISO3': 'MMR'}},
  {'attributes': {'OBJECTID': 30,
    'Country_Region': 'Burundi',
    'Last_Update': 1644862830000,
    'Lat': -3.3731,
    'Long_': 29.9189,
    'Confirmed': 37856,
    'Deaths': 38,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 318.36428574372,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.100380388841927,
    'UID': 108,
    'ISO3': 'BDI'}},
  {'attributes': {'OBJECTID': 31,
    'Country_Region': 'Cabo Verde',
    'Last_Update': 1644862830000,
    'Lat': 16.5388,
    'Long_': -23.0418,
    'Confirmed': 55842,
    'Deaths': 400,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 10043.7419512651,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.716306722538591,
    'UID': 132,
    'ISO3': 'CPV'}},
  {'attributes': {'OBJECTID': 32,
    'Country_Region': 'Cambodia',
    'Last_Update': 1644862830000,
    'Lat': 11.55,
    'Long_': 104.9167,
    'Confirmed': 123955,
    'Deaths': 3015,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 741.403283730799,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 2.43233431487233,
    'UID': 116,
    'ISO3': 'KHM'}},
  {'attributes': {'OBJECTID': 33,
    'Country_Region': 'Cameroon',
    'Last_Update': 1644862830000,
    'Lat': 3.848,
    'Long_': 11.5021,
    'Confirmed': 118675,
    'Deaths': 1915,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 447.056460471582,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.6136507267748,
    'UID': 120,
    'ISO3': 'CMR'}},
  {'attributes': {'OBJECTID': 34,
    'Country_Region': 'Canada',
    'Last_Update': 1644862830000,
    'Lat': 60.001,
    'Long_': -95.001,
    'Confirmed': 3193364,
    'Deaths': 35498,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 8349.51362894232,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.11161771724113,
    'UID': 124,
    'ISO3': 'CAN'}},
  {'attributes': {'OBJECTID': 35,
    'Country_Region': 'Central African Republic',
    'Last_Update': 1644862830000,
    'Lat': 6.6111,
    'Long_': 20.9394,
    'Confirmed': 14154,
    'Deaths': 111,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 293.057797441034,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 0.784230606189063,
    'UID': 140,
    'ISO3': 'CAF'}},
  {'attributes': {'OBJECTID': 36,
    'Country_Region': 'Chad',
    'Last_Update': 1644862830000,
    'Lat': 15.4542,
    'Long_': 18.7322,
    'Confirmed': 7216,
    'Deaths': 190,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 43.9307314156295,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 2.6330376940133,
    'UID': 148,
    'ISO3': 'TCD'}},
  {'attributes': {'OBJECTID': 37,
    'Country_Region': 'Chile',
    'Last_Update': 1644862830000,
    'Lat': -35.6751,
    'Long_': -71.543,
    'Confirmed': 2652713,
    'Deaths': 40666,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 13876.7733707034,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.53299659631479,
    'UID': 152,
    'ISO3': 'CHL'}},
  {'attributes': {'OBJECTID': 38,
    'Country_Region': 'China',
    'Last_Update': 1644862830000,
    'Lat': 30.5928,
    'Long_': 114.3055,
    'Confirmed': 124157,
    'Deaths': 4855,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 8.7943668430011,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 3.91037154570423,
    'UID': 156,
    'ISO3': 'CHN'}},
  {'attributes': {'OBJECTID': 39,
    'Country_Region': 'Colombia',
    'Last_Update': 1644862830000,
    'Lat': 4.5709,
    'Long_': -74.2973,
    'Confirmed': 6020095,
    'Deaths': 137115,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 11831.277095064,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 2.27762186477124,
    'UID': 170,
    'ISO3': 'COL'}},
  {'attributes': {'OBJECTID': 40,
    'Country_Region': 'Comoros',
    'Last_Update': 1644862830000,
    'Lat': -11.6455,
    'Long_': 43.3333,
    'Confirmed': 8005,
    'Deaths': 160,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 920.543471386105,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.99875078076202,
    'UID': 174,
    'ISO3': 'COM'}},
  {'attributes': {'OBJECTID': 41,
    'Country_Region': 'Congo (Brazzaville)',
    'Last_Update': 1644862830000,
    'Lat': -0.228,
    'Long_': 15.8277,
    'Confirmed': 23860,
    'Deaths': 375,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 432.395835372082,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.57166806370495,
    'UID': 178,
    'ISO3': 'COG'}},
  {'attributes': {'OBJECTID': 42,
    'Country_Region': 'Congo (Kinshasa)',
    'Last_Update': 1644862830000,
    'Lat': -4.0383,
    'Long_': 21.7587,
    'Confirmed': 85776,
    'Deaths': 1316,
    'Recovered': None,
    'Active': None,
    'Incident_Rate': 95.7733981034956,
    'People_Tested': None,
    'People_Hospitalized': None,
    'Mortality_Rate': 1.53422868867749,
    'UID': 180,
    'ISO3': 'COD'}},
  {'attributes': {'OBJECTID': 43,
    'Country_Region': 'Costa Rica',
    'Last_Update': 1644862830000,
    'Lat': 9.7489,
    'Long_': -83.7534,
    'Confirmed': 757093,
    'Deaths': 7772,
    'Recovered': None,

In [87]:
json.keys()

dict_keys(['objectIdFieldName', 'uniqueIdField', 'globalIdFieldName', 'geometryType', 'spatialReference', 'fields', 'features'])

In [88]:
df_api_fields = pd.DataFrame(json['fields'])
df_api_fields

                   name                  type                alias       sqlType domain defaultValue  length
0              OBJECTID      esriFieldTypeOID             OBJECTID  sqlTypeOther   None         None     NaN
1        Country_Region   esriFieldTypeString       Country/Region  sqlTypeOther   None         None     256
2           Last_Update     esriFieldTypeDate          Last Update  sqlTypeOther   None         None       8
3                   Lat   esriFieldTypeDouble             Latitude  sqlTypeOther   None         None     NaN
4                 Long_   esriFieldTypeDouble            Longitude  sqlTypeOther   None         None     NaN
5             Confirmed  esriFieldTypeInteger            Confirmed  sqlTypeOther   None         None     NaN
6                Deaths  esriFieldTypeInteger               Deaths  sqlTypeOther   None         None     NaN
7             Recovered  esriFieldTypeInteger            Recovered  sqlTypeOther   None         None     NaN
8                Active  esriFieldTypeInteger               Active  sqlTypeOther   None         None     NaN
9         Incident_Rate   esriFieldTypeDouble        Incident Rate  sqlTypeOther   None         None     NaN
10        People_Tested  esriFieldTypeInteger        People Tested  sqlTypeOther   None         None     NaN
11  People_Hospitalized  esriFieldTypeInteger  People_Hospitalized  sqlTypeOther   None         None     NaN
12       Mortality_Rate   esriFieldTypeDouble       Mortality_Rate  sqlTypeOther   None         None     NaN
13                  UID  esriFieldTypeInteger                  UID  sqlTypeOther   None         None     NaN
14                 ISO3   esriFieldTypeString                 ISO3  sqlTypeOther   None         None       3

In [89]:
# Printing the first object to see what the keys are in the API
print(json['features'][0]['attributes'])

{'OBJECTID': 1, 'Country_Region': 'Afghanistan', 'Last_Update': 1644862830000, 'Lat': 33.93911, 'Long_': 67.709953, 'Confirmed': 171246, 'Deaths': 7501, 'Recovered': None, 'Active': None, 'Incident_Rate': 439.90058553998, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 4.38024829777046, 'UID': 4, 'ISO3': 'AFG'}

In [90]:
# Creating a for loop to add all data needed in API to a dataframe
rows = []
for row in json['features']:
    rows.append(row['attributes'])
print(rows)

[{'OBJECTID': 1, 'Country_Region': 'Afghanistan', 'Last_Update': 1644862830000, 'Lat': 33.93911, 'Long_': 67.709953, 'Confirmed': 171246, 'Deaths': 7501, 'Recovered': None, 'Active': None, 'Incident_Rate': 439.90058553998, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 4.38024829777046, 'UID': 4, 'ISO3': 'AFG'}, {'OBJECTID': 2, 'Country_Region': 'Albania', 'Last_Update': 1644862830000, 'Lat': 41.1533, 'Long_': 20.1683, 'Confirmed': 268304, 'Deaths': 3414, 'Recovered': None, 'Active': None, 'Incident_Rate': 9323.2330252276, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.2724372353748, 'UID': 8, 'ISO3': 'ALB'}, {'OBJECTID': 3, 'Country_Region': 'Algeria', 'Last_Update': 1644862830000, 'Lat': 28.0339, 'Long_': 1.6596, 'Confirmed': 261752, 'Deaths': 6729, 'Recovered': None, 'Active': None, 'Incident_Rate': 596.911685772218, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.57075399614903, 'UID': 12, 'ISO3': 'DZA'}, {'OBJECTID': 4, 'Country_Region': 'Andorra', 'Last_Update': 1644862830000, 'Lat': 42.5063, 'Long_': 1.5218, 'Confirmed': 37140, 'Deaths': 148, 'Recovered': None, 'Active': None, 'Incident_Rate': 48068.3362453892, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.398492191707054, 'UID': 20, 'ISO3': 'AND'}, {'OBJECTID': 5, 'Country_Region': 'Angola', 'Last_Update': 1644862830000, 'Lat': -11.2027, 'Long_': 17.8739, 'Confirmed': 98514, 'Deaths': 1898, 'Recovered': None, 'Active': None, 'Incident_Rate': 299.741972529403, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.92662971760359, 'UID': 24, 'ISO3': 'AGO'}, {'OBJECTID': 6, 'Country_Region': 'Antarctica', 'Last_Update': 1644862830000, 'Lat': -71.9499, 'Long_': 23.347, 'Confirmed': 11, 'Deaths': 0, 'Recovered': None, 'Active': None, 'Incident_Rate': None, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0, 'UID': 10, 'ISO3': 'ATA'}, {'OBJECTID': 7, 'Country_Region': 'Antigua and Barbuda', 'Last_Update': 1644862830000, 'Lat': 17.0608, 'Long_': -61.7964, 'Confirmed': 7331, 'Deaths': 134, 'Recovered': None, 'Active': None, 'Incident_Rate': 7486.11224573156, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.82785431728277, 'UID': 28, 'ISO3': 'ATG'}, {'OBJECTID': 8, 'Country_Region': 'Argentina', 'Last_Update': 1644862830000, 'Lat': -38.4161, 'Long_': -63.6167, 'Confirmed': 8734551, 'Deaths': 124081, 'Recovered': None, 'Active': None, 'Incident_Rate': 19326.0334920229, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.42057674172376, 'UID': 32, 'ISO3': 'ARG'}, {'OBJECTID': 9, 'Country_Region': 'Armenia', 'Last_Update': 1644862830000, 'Lat': 40.0691, 'Long_': 45.0382, 'Confirmed': 407074, 'Deaths': 8186, 'Recovered': None, 'Active': None, 'Incident_Rate': 13737.4908630233, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.01093658646831, 'UID': 51, 'ISO3': 'ARM'}, {'OBJECTID': 10, 'Country_Region': 'Australia', 'Last_Update': 1644862830000, 'Lat': -25, 'Long_': 133, 'Confirmed': 2921725, 'Deaths': 4618, 'Recovered': None, 'Active': None, 'Incident_Rate': 11475.8814911409, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.158057312033131, 'UID': 36, 'ISO3': 'AUS'}, {'OBJECTID': 11, 'Country_Region': 'Austria', 'Last_Update': 1644862830000, 'Lat': 47.5162, 'Long_': 14.5501, 'Confirmed': 2299229, 'Deaths': 14392, 'Recovered': None, 'Active': None, 'Incident_Rate': 25528.8350506307, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.625948959412046, 'UID': 40, 'ISO3': 'AUT'}, {'OBJECTID': 12, 'Country_Region': 'Azerbaijan', 'Last_Update': 1644862830000, 'Lat': 40.1431, 'Long_': 47.5769, 'Confirmed': 747918, 'Deaths': 9077, 'Recovered': None, 'Active': None, 'Incident_Rate': 7376.51732019617, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.21363571942379, 'UID': 31, 'ISO3': 'AZE'}, {'OBJECTID': 13, 'Country_Region': 'Bahamas', 'Last_Update': 1644862830000, 'Lat': 25.025885, 'Long_': -78.035889, 'Confirmed': 32931, 'Deaths': 766, 'Recovered': None, 'Active': None, 'Incident_Rate': 8374.10489055253, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.32607573411072, 'UID': 44, 'ISO3': 'BHS'}, {'OBJECTID': 14, 'Country_Region': 'Bahrain', 'Last_Update': 1644862830000, 'Lat': 26.0275, 'Long_': 50.55, 'Confirmed': 463805, 'Deaths': 1427, 'Recovered': None, 'Active': None, 'Incident_Rate': 27257.2657343192, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.307672405429006, 'UID': 48, 'ISO3': 'BHR'}, {'OBJECTID': 15, 'Country_Region': 'Bangladesh', 'Last_Update': 1644862830000, 'Lat': 23.685, 'Long_': 90.3563, 'Confirmed': 1914356, 'Deaths': 28838, 'Recovered': None, 'Active': None, 'Incident_Rate': 1162.40401483561, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.50640737668438, 'UID': 50, 'ISO3': 'BGD'}, {'OBJECTID': 16, 'Country_Region': 'Barbados', 'Last_Update': 1644862830000, 'Lat': 13.1939, 'Long_': -59.5432, 'Confirmed': 51624, 'Deaths': 299, 'Recovered': None, 'Active': None, 'Incident_Rate': 17964.2343869075, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.579187974585464, 'UID': 52, 'ISO3': 'BRB'}, {'OBJECTID': 17, 'Country_Region': 'Belarus', 'Last_Update': 1644862830000, 'Lat': 53.7098, 'Long_': 27.9534, 'Confirmed': 838571, 'Deaths': 6265, 'Recovered': None, 'Active': None, 'Incident_Rate': 8874.4048381889, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.747104300053305, 'UID': 112, 'ISO3': 'BLR'}, {'OBJECTID': 18, 'Country_Region': 'Belgium', 'Last_Update': 1644862830000, 'Lat': 50.8333, 'Long_': 4.469936, 'Confirmed': 3421081, 'Deaths': 29624, 'Recovered': None, 'Active': None, 'Incident_Rate': 29767.5790969195, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.865925127174715, 'UID': 56, 'ISO3': 'BEL'}, {'OBJECTID': 19, 'Country_Region': 'Belize', 'Last_Update': 1644862830000, 'Lat': 17.1899, 'Long_': -88.4976, 'Confirmed': 55183, 'Deaths': 631, 'Recovered': None, 'Active': None, 'Incident_Rate': 13878.2911365345, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.14346809705888, 'UID': 84, 'ISO3': 'BLZ'}, {'OBJECTID': 20, 'Country_Region': 'Benin', 'Last_Update': 1644862830000, 'Lat': 9.3077, 'Long_': 2.3158, 'Confirmed': 26552, 'Deaths': 163, 'Recovered': None, 'Active': None, 'Incident_Rate': 219.018117166774, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.61388972582103, 'UID': 204, 'ISO3': 'BEN'}, {'OBJECTID': 21, 'Country_Region': 'Bhutan', 'Last_Update': 1644862830000, 'Lat': 27.5142, 'Long_': 90.4336, 'Confirmed': 7666, 'Deaths': 5, 'Recovered': None, 'Active': None, 'Incident_Rate': 993.504507446748, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.0652230628750326, 'UID': 64, 'ISO3': 'BTN'}, {'OBJECTID': 22, 'Country_Region': 'Bolivia', 'Last_Update': 1644862830000, 'Lat': -16.2902, 'Long_': -63.5887, 'Confirmed': 883382, 'Deaths': 21284, 'Recovered': None, 'Active': None, 'Incident_Rate': 7567.71871294075, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.40937669094457, 'UID': 68, 'ISO3': 'BOL'}, {'OBJECTID': 23, 'Country_Region': 'Bosnia and Herzegovina', 'Last_Update': 1644862830000, 'Lat': 43.9159, 'Long_': 17.6791, 'Confirmed': 364610, 'Deaths': 15096, 'Recovered': None, 'Active': None, 'Incident_Rate': 11113.3971284574, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 4.14031430843915, 'UID': 70, 'ISO3': 'BIH'}, {'OBJECTID': 24, 'Country_Region': 'Botswana', 'Last_Update': 1644862830000, 'Lat': -22.3285, 'Long_': 24.6849, 'Confirmed': 259655, 'Deaths': 2597, 'Recovered': None, 'Active': None, 'Incident_Rate': 11041.5138468081, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.00017330688799, 'UID': 72, 'ISO3': 'BWA'}, {'OBJECTID': 25, 'Country_Region': 'Brazil', 'Last_Update': 1644862830000, 'Lat': -14.235, 'Long_': -51.9253, 'Confirmed': 27492904, 'Deaths': 638673, 'Recovered': None, 'Active': None, 'Incident_Rate': 12934.2211334432, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.32304670325114, 'UID': 76, 'ISO3': 'BRA'}, {'OBJECTID': 26, 'Country_Region': 'Brunei', 'Last_Update': 1644862830000, 'Lat': 4.5353, 'Long_': 114.7277, 'Confirmed': 23992, 'Deaths': 98, 'Recovered': None, 'Active': None, 'Incident_Rate': 5484.09881069664, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.408469489829943, 'UID': 96, 'ISO3': 'BRN'}, {'OBJECTID': 27, 'Country_Region': 'Bulgaria', 'Last_Update': 1644862830000, 'Lat': 42.7339, 'Long_': 25.4858, 'Confirmed': 1036824, 'Deaths': 34404, 'Recovered': None, 'Active': None, 'Incident_Rate': 14921.6695246203, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 3.31821022661512, 'UID': 100, 'ISO3': 'BGR'}, {'OBJECTID': 28, 'Country_Region': 'Burkina Faso', 'Last_Update': 1644862830000, 'Lat': 12.2383, 'Long_': -1.5616, 'Confirmed': 20721, 'Deaths': 375, 'Recovered': None, 'Active': None, 'Incident_Rate': 99.1279932267083, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.8097582163023, 'UID': 854, 'ISO3': 'BFA'}, {'OBJECTID': 29, 'Country_Region': 'Burma', 'Last_Update': 1644862830000, 'Lat': 21.9162, 'Long_': 95.956, 'Confirmed': 548357, 'Deaths': 19311, 'Recovered': None, 'Active': None, 'Incident_Rate': 1007.82774512986, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 3.52161092135233, 'UID': 104, 'ISO3': 'MMR'}, {'OBJECTID': 30, 'Country_Region': 'Burundi', 'Last_Update': 1644862830000, 'Lat': -3.3731, 'Long_': 29.9189, 'Confirmed': 37856, 'Deaths': 38, 'Recovered': None, 'Active': None, 'Incident_Rate': 318.36428574372, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.100380388841927, 'UID': 108, 'ISO3': 'BDI'}, {'OBJECTID': 31, 'Country_Region': 'Cabo Verde', 'Last_Update': 1644862830000, 'Lat': 16.5388, 'Long_': -23.0418, 'Confirmed': 55842, 'Deaths': 400, 'Recovered': None, 'Active': None, 'Incident_Rate': 10043.7419512651, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.716306722538591, 'UID': 132, 'ISO3': 'CPV'}, {'OBJECTID': 32, 'Country_Region': 'Cambodia', 'Last_Update': 1644862830000, 'Lat': 11.55, 'Long_': 104.9167, 'Confirmed': 123955, 'Deaths': 3015, 'Recovered': None, 'Active': None, 'Incident_Rate': 741.403283730799, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.43233431487233, 'UID': 116, 'ISO3': 'KHM'}, {'OBJECTID': 33, 'Country_Region': 'Cameroon', 'Last_Update': 1644862830000, 'Lat': 3.848, 'Long_': 11.5021, 'Confirmed': 118675, 'Deaths': 1915, 'Recovered': None, 'Active': None, 'Incident_Rate': 447.056460471582, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.6136507267748, 'UID': 120, 'ISO3': 'CMR'}, {'OBJECTID': 34, 'Country_Region': 'Canada', 'Last_Update': 1644862830000, 'Lat': 60.001, 'Long_': -95.001, 'Confirmed': 3193364, 'Deaths': 35498, 'Recovered': None, 'Active': None, 'Incident_Rate': 8349.51362894232, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.11161771724113, 'UID': 124, 'ISO3': 'CAN'}, {'OBJECTID': 35, 'Country_Region': 'Central African Republic', 'Last_Update': 1644862830000, 'Lat': 6.6111, 'Long_': 20.9394, 'Confirmed': 14154, 'Deaths': 111, 'Recovered': None, 'Active': None, 'Incident_Rate': 293.057797441034, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.784230606189063, 'UID': 140, 'ISO3': 'CAF'}, {'OBJECTID': 36, 'Country_Region': 'Chad', 'Last_Update': 1644862830000, 'Lat': 15.4542, 'Long_': 18.7322, 'Confirmed': 7216, 'Deaths': 190, 'Recovered': None, 'Active': None, 'Incident_Rate': 43.9307314156295, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.6330376940133, 'UID': 148, 'ISO3': 'TCD'}, {'OBJECTID': 37, 'Country_Region': 'Chile', 'Last_Update': 1644862830000, 'Lat': -35.6751, 'Long_': -71.543, 'Confirmed': 2652713, 'Deaths': 40666, 'Recovered': None, 'Active': None, 'Incident_Rate': 13876.7733707034, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.53299659631479, 'UID': 152, 'ISO3': 'CHL'}, {'OBJECTID': 38, 'Country_Region': 'China', 'Last_Update': 1644862830000, 'Lat': 30.5928, 'Long_': 114.3055, 'Confirmed': 124157, 'Deaths': 4855, 'Recovered': None, 'Active': None, 'Incident_Rate': 8.7943668430011, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 3.91037154570423, 'UID': 156, 'ISO3': 'CHN'}, {'OBJECTID': 39, 'Country_Region': 'Colombia', 'Last_Update': 1644862830000, 'Lat': 4.5709, 'Long_': -74.2973, 'Confirmed': 6020095, 'Deaths': 137115, 'Recovered': None, 'Active': None, 'Incident_Rate': 11831.277095064, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.27762186477124, 'UID': 170, 'ISO3': 'COL'}, {'OBJECTID': 40, 'Country_Region': 'Comoros', 'Last_Update': 1644862830000, 'Lat': -11.6455, 'Long_': 43.3333, 'Confirmed': 8005, 'Deaths': 160, 'Recovered': None, 'Active': None, 'Incident_Rate': 920.543471386105, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.99875078076202, 'UID': 174, 'ISO3': 'COM'}, {'OBJECTID': 41, 'Country_Region': 'Congo (Brazzaville)', 'Last_Update': 1644862830000, 'Lat': -0.228, 'Long_': 15.8277, 'Confirmed': 23860, 'Deaths': 375, 'Recovered': None, 'Active': None, 'Incident_Rate': 432.395835372082, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.57166806370495, 'UID': 178, 'ISO3': 'COG'}, {'OBJECTID': 42, 'Country_Region': 'Congo (Kinshasa)', 'Last_Update': 1644862830000, 'Lat': -4.0383, 'Long_': 21.7587, 'Confirmed': 85776, 'Deaths': 1316, 'Recovered': None, 'Active': None, 'Incident_Rate': 95.7733981034956, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.53422868867749, 'UID': 180, 'ISO3': 'COD'}, {'OBJECTID': 43, 'Country_Region': 'Costa Rica', 'Last_Update': 1644862830000, 'Lat': 9.7489, 'Long_': -83.7534, 'Confirmed': 757093, 'Deaths': 7772, 'Recovered': None, 'Active': None, 'Incident_Rate': 14862.1134116747, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.02655816392438, 'UID': 188, 'ISO3': 'CRI'}, {'OBJECTID': 44, 'Country_Region': "Cote d'Ivoire", 'Last_Update': 1644862830000, 'Lat': 7.54, 'Long_': -5.5471, 'Confirmed': 81118, 'Deaths': 789, 'Recovered': None, 'Active': None, 'Incident_Rate': 307.518213378244, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.97265711679282, 'UID': 384, 'ISO3': 'CIV'}, {'OBJECTID': 45, 'Country_Region': 'Croatia', 'Last_Update': 1644862830000, 'Lat': 45.1, 'Long_': 15.2, 'Confirmed': 1018367, 'Deaths': 14537, 'Recovered': None, 'Active': None, 'Incident_Rate': 24806.3463822581, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.42748144824017, 'UID': 191, 'ISO3': 'HRV'}, {'OBJECTID': 46, 'Country_Region': 'Cuba', 'Last_Update': 1644862830000, 'Lat': 21.521757, 'Long_': -77.781167, 'Confirmed': 1061524, 'Deaths': 8476, 'Recovered': None, 'Active': None, 'Incident_Rate': 9371.94304106363, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.79847464588648, 'UID': 192, 'ISO3': 'CUB'}, {'OBJECTID': 47, 'Country_Region': 'Cyprus', 'Last_Update': 1644862830000, 'Lat': 35.1264, 'Long_': 33.4299, 'Confirmed': 290110, 'Deaths': 785, 'Recovered': None, 'Active': None, 'Incident_Rate': 24028.4388844761, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.270587018717038, 'UID': 196, 'ISO3': 'CYP'}, {'OBJECTID': 48, 'Country_Region': 'Czechia', 'Last_Update': 1644862830000, 'Lat': 49.8175, 'Long_': 15.473, 'Confirmed': 3403469, 'Deaths': 37873, 'Recovered': None, 'Active': None, 'Incident_Rate': 31781.442904657, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.11277640548511, 'UID': 203, 'ISO3': 'CZE'}, {'OBJECTID': 49, 'Country_Region': 'Denmark', 'Last_Update': 1644862830000, 'Lat': 56.2639, 'Long_': 9.5018, 'Confirmed': 2397007, 'Deaths': 4139, 'Recovered': None, 'Active': None, 'Incident_Rate': 41064.2373338098, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.17267367179153, 'UID': 208, 'ISO3': 'DNK'}, {'OBJECTID': 50, 'Country_Region': 'Diamond Princess', 'Last_Update': 1644862830000, 'Lat': None, 'Long_': None, 'Confirmed': 712, 'Deaths': 13, 'Recovered': None, 'Active': None, 'Incident_Rate': None, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.82584269662921, 'UID': 9999, 'ISO3': None}, {'OBJECTID': 51, 'Country_Region': 'Djibouti', 'Last_Update': 1644862830000, 'Lat': 11.8251, 'Long_': 42.5903, 'Confirmed': 15534, 'Deaths': 189, 'Recovered': None, 'Active': None, 'Incident_Rate': 1572.26402375704, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.21668597914253, 'UID': 262, 'ISO3': 'DJI'}, {'OBJECTID': 52, 'Country_Region': 'Dominica', 'Last_Update': 1644862830000, 'Lat': 15.415, 'Long_': -61.371, 'Confirmed': 10414, 'Deaths': 53, 'Recovered': None, 'Active': None, 'Incident_Rate': 14465.6971010265, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.508930286153255, 'UID': 212, 'ISO3': 'DMA'}, {'OBJECTID': 53, 'Country_Region': 'Dominican Republic', 'Last_Update': 1644862830000, 'Lat': 18.7357, 'Long_': -70.1627, 'Confirmed': 569446, 'Deaths': 4347, 'Recovered': None, 'Active': None, 'Incident_Rate': 5249.36430115901, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.763373524443055, 'UID': 214, 'ISO3': 'DOM'}, {'OBJECTID': 54, 'Country_Region': 'Ecuador', 'Last_Update': 1644862830000, 'Lat': -1.8312, 'Long_': -78.1834, 'Confirmed': 781470, 'Deaths': 34854, 'Recovered': None, 'Active': None, 'Incident_Rate': 4429.33368701348, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 4.46005604821682, 'UID': 218, 'ISO3': 'ECU'}, {'OBJECTID': 55, 'Country_Region': 'Egypt', 'Last_Update': 1644862830000, 'Lat': 26.820553, 'Long_': 30.802498, 'Confirmed': 452821, 'Deaths': 23292, 'Recovered': None, 'Active': None, 'Incident_Rate': 442.491465944253, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 5.1437543753492, 'UID': 818, 'ISO3': 'EGY'}, {'OBJECTID': 56, 'Country_Region': 'El Salvador', 'Last_Update': 1644862830000, 'Lat': 13.7942, 'Long_': -88.8965, 'Confirmed': 147786, 'Deaths': 4002, 'Recovered': None, 'Active': None, 'Incident_Rate': 2278.46778106321, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.70796963176485, 'UID': 222, 'ISO3': 'SLV'}, {'OBJECTID': 57, 'Country_Region': 'Equatorial Guinea', 'Last_Update': 1644862830000, 'Lat': 1.6508, 'Long_': 10.2679, 'Confirmed': 15859, 'Deaths': 182, 'Recovered': None, 'Active': None, 'Incident_Rate': 1130.37559204126, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.1476133425815, 'UID': 226, 'ISO3': 'GNQ'}, {'OBJECTID': 58, 'Country_Region': 'Eritrea', 'Last_Update': 1644862830000, 'Lat': 15.1794, 'Long_': 39.7823, 'Confirmed': 9668, 'Deaths': 103, 'Recovered': None, 'Active': None, 'Incident_Rate': 272.612406797038, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 1.06537029375259, 'UID': 232, 'ISO3': 'ERI'}, {'OBJECTID': 59, 'Country_Region': 'Estonia', 'Last_Update': 1644862830000, 'Lat': 58.5953, 'Long_': 25.0136, 'Confirmed': 423499, 'Deaths': 2115, 'Recovered': None, 'Active': None, 'Incident_Rate': 31925.1073658596, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 0.499410860474287, 'UID': 233, 'ISO3': 'EST'}, {'OBJECTID': 60, 'Country_Region': 'Eswatini', 'Last_Update': 1644862830000, 'Lat': -26.5225, 'Long_': 31.4659, 'Confirmed': 68795, 'Deaths': 1383, 'Recovered': None, 'Active': None, 'Incident_Rate': 5929.76510217521, 'People_Tested': None, 'People_Hospitalized': None, 'Mortality_Rate': 2.01032051747947, 'UID': 748, 'ISO3': 'SWZ'}, {'OBJEC

In [91]:
# Converting the list to a dataframe
df_api_features = pd.DataFrame(rows)
df_api_features

     OBJECTID                    Country_Region    Last_Update  Lat  Long_  Confirmed  Deaths Recovered Active  Incident_Rate People_Tested People_Hospitalized  Mortality_Rate   UID  ISO3
0           1                       Afghanistan  1644862830000   34     68     171246    7501      None   None            440          None                None               4     4   AFG
1           2                           Albania  1644862830000   41     20     268304    3414      None   None          9,323          None                None               1     8   ALB
2           3                           Algeria  1644862830000   28      2     261752    6729      None   None            597          None                None               3    12   DZA
3           4                           Andorra  1644862830000   43      2      37140     148      None   None         48,068          None                None               0    20   AND
4           5                            Angola  1644862830000  -11     18      98514    1898      None   None            300          None                None               2    24   AGO
5           6                        Antarctica  1644862830000  -72     23         11       0      None   None            NaN          None                None               0    10   ATA
6           7               Antigua and Barbuda  1644862830000   17    -62       7331     134      None   None          7,486          None                None               2    28   ATG
7           8                         Argentina  1644862830000  -38    -64    8734551  124081      None   None         19,326          None                None               1    32   ARG
8           9                           Armenia  1644862830000   40     45     407074    8186      None   None         13,737          None                None               2    51   ARM
9          10                         Australia  1644862830000  -25    133    2921725    4618      None   None         11,476          None                None               0    36   AUS
10         11                           Austria  1644862830000   48     15    2299229   14392      None   None         25,529          None                None               1    40   AUT
11         12                        Azerbaijan  1644862830000   40     48     747918    9077      None   None          7,377          None                None               1    31   AZE
12         13                           Bahamas  1644862830000   25    -78      32931     766      None   None          8,374          None                None               2    44   BHS
13         14                           Bahrain  1644862830000   26     51     463805    1427      None   None         27,257          None                None               0    48   BHR
14         15                        Bangladesh  1644862830000   24     90    1914356   28838      None   None          1,162          None                None               2    50   BGD
15         16                          Barbados  1644862830000   13    -60      51624     299      None   None         17,964          None                None               1    52   BRB
16         17                           Belarus  1644862830000   54     28     838571    6265      None   None          8,874          None                None               1   112   BLR
17         18                           Belgium  1644862830000   51      4    3421081   29624      None   None         29,768          None                None               1    56   BEL
18         19                            Belize  1644862830000   17    -88      55183     631      None   None         13,878          None                None               1    84   BLZ
19         20                             Benin  1644862830000    9      2      26552     163      None   None            219          None                None               1   204   BEN
20         21                            Bhutan  1644862830000   28     90       7666       5      None   None            994          None                None               0    64   BTN
21         22                           Bolivia  1644862830000  -16    -64     883382   21284      None   None          7,568          None                None               2    68   BOL
22         23            Bosnia and Herzegovina  1644862830000   44     18     364610   15096      None   None         11,113          None                None               4    70   BIH
23         24                          Botswana  1644862830000  -22     25     259655    2597      None   None         11,042          None                None               1    72   BWA
24         25                            Brazil  1644862830000  -14    -52   27492904  638673      None   None         12,934          None                None               2    76   BRA
25         26                            Brunei  1644862830000    5    115      23992      98      None   None          5,484          None                None               0    96   BRN
26         27                          Bulgaria  1644862830000   43     25    1036824   34404      None   None         14,922          None                None               3   100   BGR
27         28                      Burkina Faso  1644862830000   12     -2      20721     375      None   None             99          None                None               2   854   BFA
28         29                             Burma  1644862830000   22     96     548357   19311      None   None          1,008          None                None               4   104   MMR
29         30                           Burundi  1644862830000   -3     30      37856      38      None   None            318          None                None               0   108   BDI
30         31                        Cabo Verde  1644862830000   17    -23      55842     400      None   None         10,044          None                None               1   132   CPV
31         32                          Cambodia  1644862830000   12    105     123955    3015      None   None            741          None                None               2   116   KHM
32         33                          Cameroon  1644862830000    4     12     118675    1915      None   None            447          None                None               2   120   CMR
33         34                            Canada  1644862830000   60    -95    3193364   35498      None   None          8,350          None                None               1   124   CAN
34         35          Central African Republic  1644862830000    7     21      14154     111      None   None            293          None                None               1   140   CAF
35         36                              Chad  1644862830000   15     19       7216     190      None   None             44          None                None               3   148   TCD
36         37                             Chile  1644862830000  -36    -72    2652713   40666      None   None         13,877          None                None               2   152   CHL
37         38                             China  1644862830000   31    114     124157    4855      None   None              9          None                None               4   156   CHN
38         39                          Colombia  1644862830000    5    -74    6020095  137115      None   None         11,831          None                None               2   170   COL
39         40                           Comoros  1644862830000  -12     43       8005     160      None   None            921          None                None               2   174   COM
40         41               Congo (Brazzaville)  1644862830000   -0     16      23860     375      None   None            432          None                None               2   178   COG
41         42                  Congo (Kinshasa)  1644862830000   -4     22      85776    1316      None   None             96          None                None               2   180   COD
42         43                        Costa Rica  1644862830000   10    -84     757093    7772      None   None         14,862          None                None               1   188   CRI
43         44                     Cote d'Ivoire  1644862830000    8     -6      81118     789      None   None            308          None                None               1   384   CIV
44         45                           Croatia  1644862830000   45     15    1018367   14537      None   None         24,806          None                None               1   191   HRV
45         46                              Cuba  1644862830000   22    -78    1061524    8476      None   None          9,372          None                None               1   192   CUB
46         47                            Cyprus  1644862830000   35     33     290110     785      None   None         24,028          None                None               0   196   CYP
47         48                           Czechia  1644862830000   50     15    3403469   37873      None   None         31,781          None                None               1   203   CZE
48         49                           Denmark  1644862830000   56     10    2397007    4139      None   None         41,064          None                None               0   208   DNK
49         50                  Diamond Princess  1644862830000  NaN    NaN        712      13      None   None            NaN          None                None               2  9999  None
50         51                          Djibouti  1644862830000   12     43      15534     189      None   None          1,572          None                None               1   262   DJI
51         52                          Dominica  1644862830000   15    -61      10414      53      None   None         14,466          None                None               1   212   DMA
52         53                Dominican Republic  1644862830000   19    -70     569446    4347      None   None          5,249          None                None               1   214   DOM
53         54                           Ecuador  1644862830000   -2    -78     781470   34854      None   None          4,429          None                None               4   218   ECU
54         55                             Egypt  1644862830000   27     31     452821   23292      None   None            442          None                None               5   818   EGY
55         56                       El Salvador  1644862830000   14    -89     147786    4002      None   None          2,278          None                None               3   222   SLV
56         57                 Equatorial Guinea  1644862830000    2     10      15859     182      None   None          1,130          None                None               1   226   GNQ
57         58                           Eritrea  1644862830000   15     40       9668     103      None   None            273          None                None               1   232   ERI
58         59                           Estonia  1644862830000   59     25     423499    2115      None   None         31,925          None                None               0   233   EST
59         60                          Eswatini  1644862830000  -27     31      68795    1383      None   None          5,930          None                None               2   748   SWZ
60         61                          Ethiopia  1644862830000    9     40     467498    7424      None   None            407          None                None               2   231   ETH
61         62                              Fiji  1644862830000  -18    178      63476     819      None   None          7,081          None                None               1   242   FJI
62         63                           Finland  1644862830000   62     26     582383    2214      None   None         10,511          None                None               0   246   FIN
63         64                            France  1644862830000   46      2   21855090  135802      None   None         33,494          None                None               1   250   FRA
64         65                             Gabon  1644862830000   -1     12      47426     302      None   None          2,131          None                None               1   266   GAB
65         66                            Gambia  1644862830000   13    -15      11911     365      None   None            493          None                None               3   270   GMB
66         67                           Georgia  1644862830000   42     43    1458093   15577      None   None         36,551          None                None               1   268   GEO
67         68                           Germany  1644862830000   51     10   12476644  120021      None   None         15,004          None                None               1   276   DEU
68         69                             Ghana  1644862830000    8     -1     157751    1419      None   None            508          None                None               1   288   GHA
69         70                            Greece  1644862830000   39     22    2194453   24836      None   None         21,054          None                None               1   300   GRC
70         71                           Grenada  1644862830000   12    -62      13255     213      None   None         11,780          None                None               2   308   GRD
71         72                         Guatemala  1644862830000   16    -90     735957   16643      None   None          4,108          None                None               2   320   GTM
72         73                            Guinea  1644862830000   10    -10      36329     436      None   None            277          None                None               1   324   GIN
73         74                     Guinea-Bissau  1644862830000   12    -15       7849     162      None   None            399          None                None               2   624   GNB
74         75                            Guyana  1644862830000    5    -59      62156    1190      None   None          7,902          None                None               2   328   GUY
75         76                             Haiti  1644862830000   19    -72      29969     807      None   None            263          None                None               3   332   HTI
76         77                          Holy See  1644862830000   42     12         29       0      None   None          3,585          None                None               0   336   VAT
77         78                          Honduras  1644862830000   15    -86     391874   10512      None   None          3,956          None                None               3   340   HND
78         79                           Hungary  1644862830000   47     20    1717072   42631      None   None         17,774          None                None               2   348   HUN
79         80                           Iceland  1644862830000   65    -19      92127      55      None   None         26,997          None                None               0   352   ISL
80         81                             India  1644862830000   21     79   42665534  509011      None   None          3,092          None                None               1   356   IND
81         82                         Indonesia  1644862830000   -1    114    4807778  145176      None   None          1,758          None                None               3   360   IDN
82         83                              Iran  1644862830000   32     54    6835221  133886      None   None          8,138          None                None               2   364   IRN
83         84                              Iraq  1644862830000   33     44    2278582   24729      None   None          5,665          None                None               1   368   IRQ
84         85                           Ireland  1644862830000   53     -8    1255571    6291      None   None         25,428          None                None               1   372   IRL
85         86                            Israel  1644862830000   31     35    3446243    9624      None   None         39,815          None                None               0   376   ISR
86         87                             Italy  1644862830000   42     13   12134451  151296      None   None         20,070          None                None               1   380   ITA
87         88                           Jamaica  1644862830000   18    -77     127054    2739      None   None          4,291          None                None               2   388   JAM
88         89                             Japan  1644862830000   36    138    3979984   20520      None   None          3,147          None                None               1   392   JPN
89         90                            Jordan  1644862830000   31     37    1490473   13532      None   None         14,608          None                None               1   400   JOR
90         91                        Kazakhstan  1644862830000   48     67    1378771   18736      None   None          7,343          None                None               1   398   KAZ
91         92                             Kenya  1644862830000   -0     38     322473    5631      None   None            600          None                None               2   404   KEN
92         93                          Kiribati  1644862830000   -3   -169       2582       3      None   None          2,195          None                None               0   296   KIR
93         94                      Korea, South  1644862830000   36    128    1405246    7102      None   None          2,741          None                None               1   410   KOR
94         95                            Kosovo  1644862830000   43     21     223188    3076      None   None         12,328          None                None               1   383   XKS
95         96                            Kuwait  1644862830000   29     47     601307    2520      None   None         14,080          None                None               0   414   KWT
96         97                        Kyrgyzstan  1644862830000   41     75     200066    2930      None   None          3,067          None                None               1   417   KGZ
97         98                              Laos  1644862830000   20    102     139244     597      None   None          1,914          None                None               0   418   LAO
98         99                            Latvia  1644862830000   57     25     522766    5029      None   None         27,715          None                None               1   428   LVA
99        100                           Lebanon  1644862830000   34     36    1016487    9840      None   None         14,893          None                None               1   422   LBN
100       101                           Lesotho  1644862830000  -30     28      32372     696      None   None          1,511          None                None               2   426   LSO
101       102                           Liberia  1644862830000    6     -9       7358     290      None   None            145          None                None               4   430   LBR
102       103                             Libya  1644862830000   26     17     473114    6135      None   None          6,885          None                None               1   434   LBY
103       104                     Liechtenstein  1644862830000   47     10      10686      74      None   None         28,020          None                None               1   438   LIE
104       105                         Lithuania  1644862830000   55     24     820131    8134      None   None         30,127          None                None               1   440   LTU

In [92]:
# We will need 3 columns from the dataframe for the project, Country_Region, Confirmed, and Deaths
df_api = df_api_features[['Country_Region', 'Confirmed', 'Deaths']]
df_api

                       Country_Region  Confirmed  Deaths
0                         Afghanistan     171246    7501
1                             Albania     268304    3414
2                             Algeria     261752    6729
3                             Andorra      37140     148
4                              Angola      98514    1898
5                          Antarctica         11       0
6                 Antigua and Barbuda       7331     134
7                           Argentina    8734551  124081
8                             Armenia     407074    8186
9                           Australia    2921725    4618
10                            Austria    2299229   14392
11                         Azerbaijan     747918    9077
12                            Bahamas      32931     766
13                            Bahrain     463805    1427
14                         Bangladesh    1914356   28838
15                           Barbados      51624     299
16                            Belarus     838571    6265
17                            Belgium    3421081   29624
18                             Belize      55183     631
19                              Benin      26552     163
20                             Bhutan       7666       5
21                            Bolivia     883382   21284
22             Bosnia and Herzegovina     364610   15096
23                           Botswana     259655    2597
24                             Brazil   27492904  638673
25                             Brunei      23992      98
26                           Bulgaria    1036824   34404
27                       Burkina Faso      20721     375
28                              Burma     548357   19311
29                            Burundi      37856      38
30                         Cabo Verde      55842     400
31                           Cambodia     123955    3015
32                           Cameroon     118675    1915
33                             Canada    3193364   35498
34           Central African Republic      14154     111
35                               Chad       7216     190
36                              Chile    2652713   40666
37                              China     124157    4855
38                           Colombia    6020095  137115
39                            Comoros       8005     160
40                Congo (Brazzaville)      23860     375
41                   Congo (Kinshasa)      85776    1316
42                         Costa Rica     757093    7772
43                      Cote d'Ivoire      81118     789
44                            Croatia    1018367   14537
45                               Cuba    1061524    8476
46                             Cyprus     290110     785
47                            Czechia    3403469   37873
48                            Denmark    2397007    4139
49                   Diamond Princess        712      13
50                           Djibouti      15534     189
51                           Dominica      10414      53
52                 Dominican Republic     569446    4347
53                            Ecuador     781470   34854
54                              Egypt     452821   23292
55                        El Salvador     147786    4002
56                  Equatorial Guinea      15859     182
57                            Eritrea       9668     103
58                            Estonia     423499    2115
59                           Eswatini      68795    1383
60                           Ethiopia     467498    7424
61                               Fiji      63476     819
62                            Finland     582383    2214
63                             France   21855090  135802
64                              Gabon      47426     302
65                             Gambia      11911     365
66                            Georgia    1458093   15577
67                            Germany   12476644  120021
68                              Ghana     157751    1419
69                             Greece    2194453   24836
70                            Grenada      13255     213
71                          Guatemala     735957   16643
72                             Guinea      36329     436
73                      Guinea-Bissau       7849     162
74                             Guyana      62156    1190
75                              Haiti      29969     807
76                           Holy See         29       0
77                           Honduras     391874   10512
78                            Hungary    1717072   42631
79                            Iceland      92127      55
80                              India   42665534  509011
81                          Indonesia    4807778  145176
82                               Iran    6835221  133886
83                               Iraq    2278582   24729
84                            Ireland    1255571    6291
85                             Israel    3446243    9624
86                              Italy   12134451  151296
87                            Jamaica     127054    2739
88                              Japan    3979984   20520
89                             Jordan    1490473   13532
90                         Kazakhstan    1378771   18736
91                              Kenya     322473    5631
92                           Kiribati       2582       3
93                       Korea, South    1405246    7102
94                             Kosovo     223188    3076
95                             Kuwait     601307    2520
96                         Kyrgyzstan     200066    2930
97                               Laos     139244     597
98                             Latvia     522766    5029
99                            Lebanon    1016487    9840
100                           Lesotho      32372     696
101                           Liberia       7358     290
102                             Libya     473114    6135
103                     Liechtenstein      10686      74
104                         Lithuania     820131    8134
105                        Luxembourg     174856     976
106                        MS Zaandam          9       2
107                        Madagascar      62844    1335
108                            Malawi      85025    2596
109                          Malaysia    3040235   32125
110                          Maldives     159061     289
111                              Mali      30265     716
112                             Malta      70089     592
113                  Marshall Islands          7       0
114                        Mauritania      58569     972
115                         Mauritius      70862     786
116                            Mexico    5292706  312819
117                        Micronesia          1       0
118                           Moldova     485563   10962
119                            Monaco       9020      49
120                          Mongolia     875440    2146
121                        Montenegro     226467    2635
122                           Morocco    1155534   15802
123                        Mozambique     224703    2189
124                           Namibia     156765    3993
125                             Nepal     973541   11900
126                       Netherlands    5878252   21970
127                       New Zealand      21575      53
128                         Nicaragua      17791     222
129                             Niger       8711     303
130                           Nigeria     254016    3141
131                   North Macedonia     287481    8768
132                            Norway    1035753    1513
133                              Oman     367679    4211
134                          Pakistan    1486361   29801
135                             Palau       3256       4
136                            Panama     742854    7950
137                  Papua New Guinea      38481     610
138                          Paraguay     624475   17905
139                              Peru    3445680  208381
140                       Philippines    3639942   55094
141                            Poland    5388907  108137
142                          Portugal    3093723   20565
143                             Qatar     351402     658
144                           Romania    2574384   61676
145                            Russia   14102736  334093
146                            Rwanda     129298    1450
147             Saint Kitts and Nevis       5499      40
148                       Saint Lucia      22121     347
149  Saint Vincent and the Grenadines       8144     102
150                             Samoa         33       0
151                        San Marino      13861     110
152             Sao Tome and Principe       5920      71
153                      Saudi Arabia     730614    8974
154                           Senegal      85440    1957
155                            Serbia    1848040   14494
156                        Seychelles      38395     157
157                      Sierra Leone       7652     125
158                         Singapore     478577     906
159                          Slovakia    1870119   18105
160                          Slovenia     851416    6099
161                   Solomon Islands       4489      58
162                           Somalia      26203    1340
163                      South Africa    3641811   96993
164                       South Sudan      16880     137
165                             Spain   10604200   95995
166                         Sri Lanka     629347   15844
167                             Sudan      59631    3831
168              Summer Olympics 2020        865       0
169                          Suriname      77036    1299
170                            Sweden    2397330   16501
171                       Switzerland    2586724   12963
172                             Syria      52751    3029
173                           Taiwan*      19621     851
174                        Tajikistan      17765     125
175                          Tanzania      33436     792
176                          Thailand    2608227   22462
177                       Timor-Leste      21748     124
178                              Togo      36660     271
179                             Tonga        141       0
180               Trinidad and Tobago     120385    3526
181                           Tunisia     967052   27119
182                            Turkey   12908321   90542
183                                US   77808188  920621
184                            Uganda     162755    3575
185                           Ukraine    4753922  109788
186              United Arab Emirates     869428    2287
187                    United Kingdom   18474171  160163
188                           Uruguay     777490    6756
189                        Uzbekistan     233761    1604
190                           Vanuatu          7       1
191                         Venezuela     505947    5549
192                           Vietnam    2540273   39037
193                West Bank and Gaza     600128    5215
194              Winter Olympics 2022        501       0
195                             Yemen      11679    2107
196                            Zambia     309502    3937
197                          Zimbabwe     231381    5374

In [93]:
# Renaming the columns
df_api.columns = ['Country', 'Confirmed Cases', 'Deaths']
df_api

                              Country  Confirmed Cases  Deaths
0                         Afghanistan           171246    7501
1                             Albania           268304    3414
2                             Algeria           261752    6729
3                             Andorra            37140     148
4                              Angola            98514    1898
5                          Antarctica               11       0
6                 Antigua and Barbuda             7331     134
7                           Argentina          8734551  124081
8                             Armenia           407074    8186
9                           Australia          2921725    4618
10                            Austria          2299229   14392
11                         Azerbaijan           747918    9077
12                            Bahamas            32931     766
13                            Bahrain           463805    1427
14                         Bangladesh          1914356   28838
15                           Barbados            51624     299
16                            Belarus           838571    6265
17                            Belgium          3421081   29624
18                             Belize            55183     631
19                              Benin            26552     163
20                             Bhutan             7666       5
21                            Bolivia           883382   21284
22             Bosnia and Herzegovina           364610   15096
23                           Botswana           259655    2597
24                             Brazil         27492904  638673
25                             Brunei            23992      98
26                           Bulgaria          1036824   34404
27                       Burkina Faso            20721     375
28                              Burma           548357   19311
29                            Burundi            37856      38
30                         Cabo Verde            55842     400
31                           Cambodia           123955    3015
32                           Cameroon           118675    1915
33                             Canada          3193364   35498
34           Central African Republic            14154     111
35                               Chad             7216     190
36                              Chile          2652713   40666
37                              China           124157    4855
38                           Colombia          6020095  137115
39                            Comoros             8005     160
40                Congo (Brazzaville)            23860     375
41                   Congo (Kinshasa)            85776    1316
42                         Costa Rica           757093    7772
43                      Cote d'Ivoire            81118     789
44                            Croatia          1018367   14537
45                               Cuba          1061524    8476
46                             Cyprus           290110     785
47                            Czechia          3403469   37873
48                            Denmark          2397007    4139
49                   Diamond Princess              712      13
50                           Djibouti            15534     189
51                           Dominica            10414      53
52                 Dominican Republic           569446    4347
53                            Ecuador           781470   34854
54                              Egypt           452821   23292
55                        El Salvador           147786    4002
56                  Equatorial Guinea            15859     182
57                            Eritrea             9668     103
58                            Estonia           423499    2115
59                           Eswatini            68795    1383
60                           Ethiopia           467498    7424
61                               Fiji            63476     819
62                            Finland           582383    2214
63                             France         21855090  135802
64                              Gabon            47426     302
65                             Gambia            11911     365
66                            Georgia          1458093   15577
67                            Germany         12476644  120021
68                              Ghana           157751    1419
69                             Greece          2194453   24836
70                            Grenada            13255     213
71                          Guatemala           735957   16643
72                             Guinea            36329     436
73                      Guinea-Bissau             7849     162
74                             Guyana            62156    1190
75                              Haiti            29969     807
76                           Holy See               29       0
77                           Honduras           391874   10512
78                            Hungary          1717072   42631
79                            Iceland            92127      55
80                              India         42665534  509011
81                          Indonesia          4807778  145176
82                               Iran          6835221  133886
83                               Iraq          2278582   24729
84                            Ireland          1255571    6291
85                             Israel          3446243    9624
86                              Italy         12134451  151296
87                            Jamaica           127054    2739
88                              Japan          3979984   20520
89                             Jordan          1490473   13532
90                         Kazakhstan          1378771   18736
91                              Kenya           322473    5631
92                           Kiribati             2582       3
93                       Korea, South          1405246    7102
94                             Kosovo           223188    3076
95                             Kuwait           601307    2520
96                         Kyrgyzstan           200066    2930
97                               Laos           139244     597
98                             Latvia           522766    5029
99                            Lebanon          1016487    9840
100                           Lesotho            32372     696
101                           Liberia             7358     290
102                             Libya           473114    6135
103                     Liechtenstein            10686      74
104                         Lithuania           820131    8134
105                        Luxembourg           174856     976
106                        MS Zaandam                9       2
107                        Madagascar            62844    1335
108                            Malawi            85025    2596
109                          Malaysia          3040235   32125
110                          Maldives           159061     289
111                              Mali            30265     716
112                             Malta            70089     592
113                  Marshall Islands                7       0
114                        Mauritania            58569     972
115                         Mauritius            70862     786
116                            Mexico          5292706  312819
117                        Micronesia                1       0
118                           Moldova           485563   10962
119                            Monaco             9020      49
120                          Mongolia           875440    2146
121                        Montenegro           226467    2635
122                           Morocco          1155534   15802
123                        Mozambique           224703    2189
124                           Namibia           156765    3993
125                             Nepal           973541   11900
126                       Netherlands          5878252   21970
127                       New Zealand            21575      53
128                         Nicaragua            17791     222
129                             Niger             8711     303
130                           Nigeria           254016    3141
131                   North Macedonia           287481    8768
132                            Norway          1035753    1513
133                              Oman           367679    4211
134                          Pakistan          1486361   29801
135                             Palau             3256       4
136                            Panama           742854    7950
137                  Papua New Guinea            38481     610
138                          Paraguay           624475   17905
139                              Peru          3445680  208381
140                       Philippines          3639942   55094
141                            Poland          5388907  108137
142                          Portugal          3093723   20565
143                             Qatar           351402     658
144                           Romania          2574384   61676
145                            Russia         14102736  334093
146                            Rwanda           129298    1450
147             Saint Kitts and Nevis             5499      40
148                       Saint Lucia            22121     347
149  Saint Vincent and the Grenadines             8144     102
150                             Samoa               33       0
151                        San Marino            13861     110
152             Sao Tome and Principe             5920      71
153                      Saudi Arabia           730614    8974
154                           Senegal            85440    1957
155                            Serbia          1848040   14494
156                        Seychelles            38395     157
157                      Sierra Leone             7652     125
158                         Singapore           478577     906
159                          Slovakia          1870119   18105
160                          Slovenia           851416    6099
161                   Solomon Islands             4489      58
162                           Somalia            26203    1340
163                      South Africa          3641811   96993
164                       South Sudan            16880     137
165                             Spain         10604200   95995
166                         Sri Lanka           629347   15844
167                             Sudan            59631    3831
168              Summer Olympics 2020              865       0
169                          Suriname            77036    1299
170                            Sweden          2397330   16501
171                       Switzerland          2586724   12963
172                             Syria            52751    3029
173                           Taiwan*            19621     851
174                        Tajikistan            17765     125
175                          Tanzania            33436     792
176                          Thailand          2608227   22462
177                       Timor-Leste            21748     124
178                              Togo            36660     271
179                             Tonga              141       0
180               Trinidad and Tobago           120385    3526
181                           Tunisia           967052   27119
182                            Turkey         12908321   90542
183                                US         77808188  920621
184                            Uganda           162755    3575
185                           Ukraine          4753922  109788
186              United Arab Emirates           869428    2287
187                    United Kingdom         18474171  160163
188                           Uruguay           777490    6756
189                        Uzbekistan           233761    1604
190                           Vanuatu                7       1
191                         Venezuela           505947    5549
192                           Vietnam          2540273   39037
193                West Bank and Gaza           600128    5215
194              Winter Olympics 2022              501       0
195                             Yemen            11679    2107
196                            Zambia           309502    3937
197                          Zimbabwe           231381    5374

In [94]:
# Checking for column types
df_api.dtypes

Country            object
Confirmed Cases     int64
Deaths              int64
dtype: object

In [95]:
# Converting Confirmed Cases and Deaths to float
df_api = df_api.astype({'Confirmed Cases' : 'float64', 'Deaths' : 'float64'})
df_api.dtypes

Country             object
Confirmed Cases    float64
Deaths             float64
dtype: object

In [96]:
# Performing a Nan check and duplicate check
# Checking for NaNs and Duplicates
print(f'Any duplicated Country: {any(df_api.duplicated())}')
print(f'Any NULLS in Confirmed: {df_api["Confirmed Cases"].isnull().values.any()}')
print(f'Any NULLS in Deaths: {df_api["Deaths"].isnull().values.any()}')
# Result shows no duplicates nor NaNs

Any duplicated Country: False
Any NULLS in Confirmed: False
Any NULLS in Deaths: False

In [97]:
# Data is in shape and ready for Phase 2
df_api

                              Country  Confirmed Cases  Deaths
0                         Afghanistan          171,246   7,501
1                             Albania          268,304   3,414
2                             Algeria          261,752   6,729
3                             Andorra           37,140     148
4                              Angola           98,514   1,898
5                          Antarctica               11       0
6                 Antigua and Barbuda            7,331     134
7                           Argentina        8,734,551 124,081
8                             Armenia          407,074   8,186
9                           Australia        2,921,725   4,618
10                            Austria        2,299,229  14,392
11                         Azerbaijan          747,918   9,077
12                            Bahamas           32,931     766
13                            Bahrain          463,805   1,427
14                         Bangladesh        1,914,356  28,838
15                           Barbados           51,624     299
16                            Belarus          838,571   6,265
17                            Belgium        3,421,081  29,624
18                             Belize           55,183     631
19                              Benin           26,552     163
20                             Bhutan            7,666       5
21                            Bolivia          883,382  21,284
22             Bosnia and Herzegovina          364,610  15,096
23                           Botswana          259,655   2,597
24                             Brazil       27,492,904 638,673
25                             Brunei           23,992      98
26                           Bulgaria        1,036,824  34,404
27                       Burkina Faso           20,721     375
28                              Burma          548,357  19,311
29                            Burundi           37,856      38
30                         Cabo Verde           55,842     400
31                           Cambodia          123,955   3,015
32                           Cameroon          118,675   1,915
33                             Canada        3,193,364  35,498
34           Central African Republic           14,154     111
35                               Chad            7,216     190
36                              Chile        2,652,713  40,666
37                              China          124,157   4,855
38                           Colombia        6,020,095 137,115
39                            Comoros            8,005     160
40                Congo (Brazzaville)           23,860     375
41                   Congo (Kinshasa)           85,776   1,316
42                         Costa Rica          757,093   7,772
43                      Cote d'Ivoire           81,118     789
44                            Croatia        1,018,367  14,537
45                               Cuba        1,061,524   8,476
46                             Cyprus          290,110     785
47                            Czechia        3,403,469  37,873
48                            Denmark        2,397,007   4,139
49                   Diamond Princess              712      13
50                           Djibouti           15,534     189
51                           Dominica           10,414      53
52                 Dominican Republic          569,446   4,347
53                            Ecuador          781,470  34,854
54                              Egypt          452,821  23,292
55                        El Salvador          147,786   4,002
56                  Equatorial Guinea           15,859     182
57                            Eritrea            9,668     103
58                            Estonia          423,499   2,115
59                           Eswatini           68,795   1,383
60                           Ethiopia          467,498   7,424
61                               Fiji           63,476     819
62                            Finland          582,383   2,214
63                             France       21,855,090 135,802
64                              Gabon           47,426     302
65                             Gambia           11,911     365
66                            Georgia        1,458,093  15,577
67                            Germany       12,476,644 120,021
68                              Ghana          157,751   1,419
69                             Greece        2,194,453  24,836
70                            Grenada           13,255     213
71                          Guatemala          735,957  16,643
72                             Guinea           36,329     436
73                      Guinea-Bissau            7,849     162
74                             Guyana           62,156   1,190
75                              Haiti           29,969     807
76                           Holy See               29       0
77                           Honduras          391,874  10,512
78                            Hungary        1,717,072  42,631
79                            Iceland           92,127      55
80                              India       42,665,534 509,011
81                          Indonesia        4,807,778 145,176
82                               Iran        6,835,221 133,886
83                               Iraq        2,278,582  24,729
84                            Ireland        1,255,571   6,291
85                             Israel        3,446,243   9,624
86                              Italy       12,134,451 151,296
87                            Jamaica          127,054   2,739
88                              Japan        3,979,984  20,520
89                             Jordan        1,490,473  13,532
90                         Kazakhstan        1,378,771  18,736
91                              Kenya          322,473   5,631
92                           Kiribati            2,582       3
93                       Korea, South        1,405,246   7,102
94                             Kosovo          223,188   3,076
95                             Kuwait          601,307   2,520
96                         Kyrgyzstan          200,066   2,930
97                               Laos          139,244     597
98                             Latvia          522,766   5,029
99                            Lebanon        1,016,487   9,840
100                           Lesotho           32,372     696
101                           Liberia            7,358     290
102                             Libya          473,114   6,135
103                     Liechtenstein           10,686      74
104                         Lithuania          820,131   8,134
105                        Luxembourg          174,856     976
106                        MS Zaandam                9       2
107                        Madagascar           62,844   1,335
108                            Malawi           85,025   2,596
109                          Malaysia        3,040,235  32,125
110                          Maldives          159,061     289
111                              Mali           30,265     716
112                             Malta           70,089     592
113                  Marshall Islands                7       0
114                        Mauritania           58,569     972
115                         Mauritius           70,862     786
116                            Mexico        5,292,706 312,819
117                        Micronesia                1       0
118                           Moldova          485,563  10,962
119                            Monaco            9,020      49
120                          Mongolia          875,440   2,146
121                        Montenegro          226,467   2,635
122                           Morocco        1,155,534  15,802
123                        Mozambique          224,703   2,189
124                           Namibia          156,765   3,993
125                             Nepal          973,541  11,900
126                       Netherlands        5,878,252  21,970
127                       New Zealand           21,575      53
128                         Nicaragua           17,791     222
129                             Niger            8,711     303
130                           Nigeria          254,016   3,141
131                   North Macedonia          287,481   8,768
132                            Norway        1,035,753   1,513
133                              Oman          367,679   4,211
134                          Pakistan        1,486,361  29,801
135                             Palau            3,256       4
136                            Panama          742,854   7,950
137                  Papua New Guinea           38,481     610
138                          Paraguay          624,475  17,905
139                              Peru        3,445,680 208,381
140                       Philippines        3,639,942  55,094
141                            Poland        5,388,907 108,137
142                          Portugal        3,093,723  20,565
143                             Qatar          351,402     658
144                           Romania        2,574,384  61,676
145                            Russia       14,102,736 334,093
146                            Rwanda          129,298   1,450
147             Saint Kitts and Nevis            5,499      40
148                       Saint Lucia           22,121     347
149  Saint Vincent and the Grenadines            8,144     102
150                             Samoa               33       0
151                        San Marino           13,861     110
152             Sao Tome and Principe            5,920      71
153                      Saudi Arabia          730,614   8,974
154                           Senegal           85,440   1,957
155                            Serbia        1,848,040  14,494
156                        Seychelles           38,395     157
157                      Sierra Leone            7,652     125
158                         Singapore          478,577     906
159                          Slovakia        1,870,119  18,105
160                          Slovenia          851,416   6,099
161                   Solomon Islands            4,489      58
162                           Somalia           26,203   1,340
163                      South Africa        3,641,811  96,993
164                       South Sudan           16,880     137
165                             Spain       10,604,200  95,995
166                         Sri Lanka          629,347  15,844
167                             Sudan           59,631   3,831
168              Summer Olympics 2020              865       0
169                          Suriname           77,036   1,299
170                            Sweden        2,397,330  16,501
171                       Switzerland        2,586,724  12,963
172                             Syria           52,751   3,029
173                           Taiwan*           19,621     851
174                        Tajikistan           17,765     125
175                          Tanzania           33,436     792
176                          Thailand        2,608,227  22,462
177                       Timor-Leste           21,748     124
178                              Togo           36,660     271
179                             Tonga              141       0
180               Trinidad and Tobago          120,385   3,526
181                           Tunisia          967,052  27,119
182                            Turkey       12,908,321  90,542
183                                US       77,808,188 920,621
184                            Uganda          162,755   3,575
185                           Ukraine        4,753,922 109,788
186              United Arab Emirates          869,428   2,287
187                    United Kingdom       18,474,171 160,163
188                           Uruguay          777,490   6,756
189                        Uzbekistan          233,761   1,604
190                           Vanuatu                7       1
191                         Venezuela          505,947   5,549
192                           Vietnam        2,540,273  39,037
193                West Bank and Gaza          600,128   5,215
194              Winter Olympics 2022              501       0
195                             Yemen           11,679   2,107
196                            Zambia          309,502   3,937
197                          Zimbabwe          231,381   5,374